### ISSUE TITLE
Panic while storing

### ISSUE THREAD

**Issue by vearutop** [puzpuzpuz/xsync#18]
I was trying to benchmark the map implementation against `sync.Map` with concurrent load, but could not because of panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56b27a]

goroutine 73 [running]:
github.com/puzpuzpuz/xsync.(*Map).doStore(0xc00009e6c0, {0xc0000b4028, 0x7}, {0x59bb40, 0xc0000d6040}, 0x0)
	/home/runner/go/pkg/mod/github.com/puzpuzpuz/xsync@v1.0.0/map.go:190 +0x21a
github.com/puzpuzpuz/xsync.(*Map).Store(...)
	/home/runner/go/pkg/mod/github.com/puzpuzpuz/xsync@v1.0.0/map.go:163
github.com/veartutop/cachex_test.xSyncMap.make({0x0, 0x0, 0x4800}, 0x0, 0xf4240)
	/home/runner/work/cache/cache/benchmark_test.go:330 +0x12a
github.com/veartutop/cachex_test.Benchmark_concurrent.func1(0xc0000cb200)
```

Reproducer: https://github.com/vearutop/cache/pull/6/checks?check_run_id=3389323336
https://github.com/vearutop/cache/blob/xsync/benchmark_test.go#L31
https://github.com/vearutop/cache/blob/xsync/benchmark_test.go#L312-L364

The benchmark stores 1e6 entries into the map and then reads "random" keys from multiple goroutines with occasional 10% writes.

Same benchmark passes for `sync.Map`, please help to check if I'm misusing this lib.

**Comment by puzpuzpuz** [comment]
Thanks for the reproducer. I'm going to check it later today.

**Comment by puzpuzpuz** [comment]
@vearutop you should be using `xsync.NewMap()` instead of plain struct initializer here:
https://github.com/vearutop/cache/blob/xsync/benchmark_test.go#L321

**Comment by puzpuzpuz** [comment]
Also, there might be something wrong with the benchmark code itself. It seems to benchmark reads only.

Even if I remove the whole:
```go
		if w == sbm.writeEvery {
			w = 0
			sbm.c.Store(string(buf), makeCachedValue(i))
			continue
		}
```
block or change `writePercent` value, the result doesn't change.

I didn't look deeper, but this looks strange to me.

**Comment by vearutop** [comment]
Thank you for the hints, indeed I missed `NewMap` and proper write configuration in benchmark, now I can see perf difference. 👍

**Comment by puzpuzpuz** [comment]
No problem at all.

One more thing to add. Does this scenario reproduce exactly what happens in bool64/cache? I specifically mean the following: all keys are pre-warmed, no new keys are being inserted, only reads and updates for existing keys happen.

The thing is that such scenario is the best possible one for `sync.Map` since it only hits fast paths for both [reads](https://github.com/golang/go/blob/6e50991d2a38058d0824f8b086677fbe9774c9f9/src/sync/map.go#L125) (a couple of atomic loads) and [writes](https://github.com/golang/go/blob/6e50991d2a38058d0824f8b086677fbe9774c9f9/src/sync/map.go#L140) (a couple of atomic loads plus a CAS). As soon as a new key is inserted, or an existing one is deleted, operations get a lot more expensive and should immediately affect the benchmark results.

P.S. I've checked the sharded map implementation in bool64/cache and I have one quick question. Did you consider added a padding into [`hashedBucket`](https://github.com/bool64/cache/blob/82886d6e5c6946752903e320e5447fb069f6eb04/sharded_map.go#L24) struct in order to prevent false sharing?
See [this PR](https://github.com/orcaman/concurrent-map/pull/101) for another library with sharded map for more details.
