### ISSUE TITLE
Map: make size() public

### ISSUE THREAD

**Issue by joy4eg** [puzpuzpuz/xsync#39]
Hello,

It would be really nice to have this function in the public API:
https://github.com/puzpuzpuz/xsync/blob/d5f0f9d5b79c39bf68bf9771f52f477262972f6f/mapof.go#L325

Thanks!

**Comment by puzpuzpuz** [comment]
Hello,

Exposing this method publicly is easy. But before doing that, I'd like to confirm one thing. The size of a concurrent map is a moving target, i.e. you will only get "up to date" size when there are no concurrent writes. Otherwise, you get a value that was actual in the past, but probably already changed. Is that what you need?

**Comment by joy4eg** [comment]
I would say in a concurrent/multi-threaded world there are no really accurate/up-to-date values. I need that value mostly for logging/debugging purposes and it's okay to have it like this. In any case, it's much better that doing a range call :)

**Comment by puzpuzpuz** [comment]
Great. We're on the same page then. I'll expose the method later today.

**Comment by puzpuzpuz** [comment]
Released in v1.3.0
